services:
  - type: web
    name: printify-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: Backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres@localhost:5432/printify
      - key: JWT_SECRET
        value: c1b7bf56afa46e7076338de49b5558418cce17ec76965a29fc7740793e568b48
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: AWS_ACCESS_KEY_ID
        value: AKIAX5ZI6RWB2EDI6OQ3
      - key: AWS_SECRET_ACCESS_KEY
        value: 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
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        value: printify-store-pdfs
